### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by Strap1** [tim-peterson/videojs-playlist#14]
How do I go about telling the player that it should be playing YouTube videos?
Passing `{ "techOrder": ["youtube"] }` in each vjs-track element, or in my JS when I instantiate the plugin, like this:
````
videojs("#video-playlist", {"techOrder": ["youtube"], "height":"auto", "width":"auto"}).ready(function (event) {
        var myPlayer = this;
          console.log(myPlayer.el().id);
          myPlayer.playlist({
            'continuous': false
          });
      });
````
?

Currently, neither option is working and the player returns a "The video could not be loaded, either because the server or network failed or because the format is not supported".

**Comment by BenjaminBini** [comment]
I have the same issue.

**Comment by da1nonly** [comment]
@BenjaminBini @Strap1 you can use this https://gist.github.com/da1nonly/c53160a5f091dbc33c39

i also added load video via hash url

**Comment by tim-peterson** [comment]
@BenjaminBini @Strap1 I merged in @da1nonly 's changes. Great working with you all!
